site_name: UnBook

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    - scheme: UnBook
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - content.tabs.link

  plugins:
    - glightbox

  font:
  text: Roboto
  code: Roboto Mono

  theme:
    logo: img/logo_UnBook.png

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - attr_list

nav:
  - Início: index.md
  - Documentação:
      - Visão do Produto e Projeto:
          - Histórico de Revisão: visao-de-produto-e-projeto/historico-de-revisao.md
          - Visão Geral do Produto: visao-de-produto-e-projeto/visao-geral-do-produto.md
          - Visão Geral do Projeto: visao-de-produto-e-projeto/visao-geral-do-projeto.md
          - Processo de Desenvolvimento de Software: visao-de-produto-e-projeto/processo-de-desenvolvimento-de-software.md        
          - Documentação das Sprints: visao-de-produto-e-projeto/documentacao-sprints.md
          - Quadro Kanban: visao-de-produto-e-projeto/kanban.md
      - Backlog do Produto: backlog-do-produto/backlog-do-produto.md
      - Estratégias de Implementação: visao-de-produto-e-projeto/estrategias.md
      - Design: 
          - Arquitetura do projeto: visao-de-produto-e-projeto/arquitetura.md
  - Entregas: 
      - Unidade 1:
          - Seminário de Processos e Ciclos de Vida: entregas/seminario.md
          - Video de Apresentação Git Pages: entregas/video-apresentacao.md
      - Unidade 2:
          - Video de Apresentação Backlog do Produto e Estratégias de Implementação: entregas/video-apresentacao-unidade2.md
      - Unidade 3:
          - Relato programação em pares: entregas/relato.md
  - Lições Aprendidas: licoes-aprendidas/licoes-aprendidas-unidade1.md
